# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: dublowduck.VB-Warships
PackageVersion: 0.1.0
Installers:
- Architecture: x86
  InstallerType: msi
  InstallerUrl: https://github.com/dublowduck/VB-Warships/releases/download/v0.1.0/VB-Warships_Setup.msi
  InstallerSha256: 09F296E62028AE13B734A24CA95231958A7D13B6153B341510B084F4391A0086
  ProductCode: '{E0999FC9-4A58-42F5-ABC1-65C2214F3647}'
ManifestType: installer
ManifestVersion: 1.1.0

